### ISSUE TITLE
Planning - PVA

### ISSUE THREAD

**Issue by Lauwy222** [InfraVroom/Information#11]
https://github.com/wustep/github-project-exporter

https://stackoverflow.com/questions/41369365/how-can-i-export-github-issues-to-excel

**Comment by justin040304** [comment]
Voor de planning wordt Github gebruikt als tool om de taken overzichtelijk te bekijken. Hiervoor wordt een een korte toelichting gegeven over de layout. 
De planning is opgedeeld in kolommen en rijen. Er is voor gekozen om de kolomnamen in het Engels te doen en de rijen deels in het Engels en Nederlands. De layout bestaat uit 6 kolommen: Title, Assignees, Status, Priority, Start-Date, Deadline en Notes. Deze kolomnamen geven weer hoe het ervoor staat met de taken. 

Note: zet deze afbeelding onder de tekst.

Image](https://user-images.githubusercontent.com/124812526/219142226-3db0380c-1b4c-4907-b8ee-d6b9e09e9a80.png


Ga naar Github / InfraVroom / projects / ToDo List / List ==> kopieer de planning

**Comment by justin040304** [comment]
Elke week worden er opdrachten gemaakt. Bij elke opdracht wordt een begin- en eindtijd gegeven. Het is de bedoeling dat de opdracht binnen deze tijd af is. Zodra dit niet het geval is, zal er eerst in overleg met de groepsleden besproken worden of de eindtijd verschoven mag/kan worden. Als daarentegen de opdracht binnen de tijd realistisch en te maken was en de opdracht niet af is, terwijl de opdracht eigenlijk wel af had moeten zijn, dan zal er in overleg met de opdrachtgever een kort gesprek moeten worden gevolgd om dit in toekomst niet weer te laten gebeuren. Als er geen verbeteringen te zien zijn in de nabije toekomst, moeten er consequenties worden genomen door de groepsleden en de opdrachtgever.
Voor de planning wordt Github gebruikt als tool om de opdrachten voor het project duidelijk te weergeven. In figuur 1 is te zien dat één opdracht uit zes kolommen bestaan. Daarin staat de 
o	Title:  wat is de titel van de opdracht
o	Assignees: wie moet de opdracht maken
o	Status: hoe staat het ervoor met de opdracht
o	Priority: hoe belangrijk is de opdracht
o	Start-Date en Deadline: vanaf wanneer tot wanneer wordt er aan de opdracht gewerkt
o	Notes: wat moet er worden gedaan om de opdracht te voltooien
In de opeenvolgende rijen daaronder worden alle opdrachten gemaakt met daarin de bijhorende informatie die in de bovenste kolommen gedefinieerd staan. 


 

![Image](https://user-images.githubusercontent.com/124812526/219656111-ccb57f7c-31fa-4d9f-a67d-16a4e7bd32c1.png)


	
versie 2
