### ISSUE TITLE
Risico's - PVA

### ISSUE THREAD

**Issue by Lauwy222** [InfraVroom/Information#13]

**Comment by justin040304** [comment]
Na het kalibreren, testen en schrijven van de software voor de sensoren en motoren, moet alle software bij elkaar worden gebracht. Het is moeilijk te zeggen hoeveel tijd dit gaat kosten, want het laten werken van de software en het zoeken naar eventuele fouten kan veel tijd in beslag nemen. De deadline voor dit onderdeel is soms dan moeilijk te bepalen.
Het verkeerd en niet goed plaatsen van componenten kan onverwachte resultaten geven, waardoor er eventueel meer tijd verloren gaat. 
Als tijdens het project een groepslid stopt of door persoonlijke omstandigheden niet door kan gaan met het project, bespreekt de groep hoe zij dit kunnen oplossen. In dit geval zal elk groepslid per week meer tijd moeten besteden aan het project.
Bij gebrek aan kennis, wordt verwacht dat er eerst goed onderzoek wordt gedaan naar hetgeen waar gebrek aan is. Als het niet lukt om de benodigde kennis te vinden, zal er naar alternatieve externen moeten worden gekeken.
Als tijdens het project extra budget nodig is voor defecte sensoren en motoren, moet in overleg met de opdrachtgever naar een oplossing worden gezocht. Bij het gebrek aan budget door defecte sensoren, motoren of andere componenten, wordt in overleg met de opdrachtgever gekeken of dit kan worden opgelost.
