### ISSUE TITLE
Projectgrenzen - PVA

### ISSUE THREAD

**Issue by Lauwy222** [InfraVroom/Information#8]

**Comment by justin040304** [comment]
Het assembleren van de robotauto. Vervolgens moet er software worden geschreven in de Arduino IDE voor de IR sensoren, ultrasonic sensoren en het aansturen van de DC motoren en servo’s.
	Daarna moeten de verschillende codes worden samengebracht tot één code. Hiermee moet worden gerealiseerd dat de robotauto bepaalde taken uitvoert, zoals 
o	Demonstratie 1: het vinden van een statisch en bewegend doel (doel 1).
o	Demonstratie 2: doel 1 + obstakels vermijden (doel 2)
o	Demonstratie 3: doel 2 + ontwijkend gedrag vertonen als er een bewegend doel is.
o	Demonstratie 4: doel 1 + doel 2 + het is in staat om in jager-modus een ander robotauto op te sporen en aan te tikken. Ook heeft het een prooi- modus om zo lang mogelijk uit handen te blijven van een ander robotautootje.
Het testen en kalibreren van de IR sensoren, sonar sensoren, DC motoren, servo motoren, Arduino Mega 2560, motorshield en eventuele bijhorende printplaten/hardware. Hiermee kan worden vastgesteld dat de bijbehorende componenten juist werken. Daarnaast kunnen er meer sensoren worden toegevoegd, zodat de robotauto zijn omgeving beter kan waarnemen (meer IR sensoren en een gyroscoop). Er kunnen kleine aanpassingen worden gemaakt aan de chassis van de robotauto.
Ook kan er een printplaat worden ontworpen op de Arduino Mega 2560 voor het makkelijker aansluiten van connectoren
Het ontwerpen van de totale chassis, de sensoren en de motoren wordt niet door de projectleden gedaan
	Het project is gestart op 7-2-2023. De projectduur duurt tot het einde van semester 2.
Voor het slagen van het project wordt verwacht dat elk groepslid elke week serieus werkt aan de robotauto. Daarnaast besteedt ieder groepslid elke week ±8 uur aan het project. Ook houden zij zich aan de afspraken en de deadlines. Ten slotte moet er  (persoonlijk) gedocumenteerd worden wat elk groepslid gedaan heeft.
